# Generated by Django 5.0.6 on 2026-05-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_sitesettings_hide_generated_data_alter_report_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payout_card',
            field=models.CharField(blank=True, max_length=19, verbose_name='Картка для виплат (Безпечна угода)'),
        ),
    ]
