# Generated by Django 5.0.6 on 2026-05-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_id_alter_orderitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_provider',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Служба доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дійсне до'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_hold_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID холдування коштів'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ТТН'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує оплати'), ('payment_held', 'Кошти зарезервовано (Очікує продавця)'), ('seller_pending', 'Очікує відправки (ТТН згенеровано)'), ('shipped', 'Відправлено (В дорозі)'), ('delivered', 'Доставлено у відділення'), ('completed', 'Угода завершена (Отримано)'), ('returned', 'Повернення (Покупець відмовився)'), ('cancelled', 'Скасовано'), ('cancelled_by_timeout', 'Скасовано (Продавець не відправив)')], default='pending', max_length=30, verbose_name='Статус'),
        ),
    ]
