# Generated by Django 5.0.6 on 2026-05-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_provider_order_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_provider',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Служба доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_hold_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ID холдування коштів'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ТТН'),
        ),
    ]
