# Generated by Django 5.0.6 on 2026-05-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Місто'),
        ),
    ]
