# Generated by Django 5.0.6 on 2026-05-22 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва фільтра (напр. Бренд)')),
                ('slug', models.SlugField(help_text='Англійською, без пробілів (напр. brand)', unique=True)),
                ('type', models.CharField(choices=[('checkbox', 'Чекбокси (множинний вибір)'), ('radio', 'Радіо-кнопки (одиничний вибір)'), ('color', 'Кольори')], default='checkbox', max_length=20, verbose_name='Тип відображення')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортування')),
            ],
            options={
                'verbose_name': 'Атрибут фільтра',
                'verbose_name_plural': 'Атрибути фільтрів',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FilterOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значення (напр. Apple)')),
                ('extra', models.CharField(blank=True, help_text='Наприклад, HEX код кольору (#000000)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортування')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.filterattribute', verbose_name='Атрибут')),
            ],
            options={
                'verbose_name': 'Опція фільтра',
                'verbose_name_plural': 'Опції фільтрів',
                'ordering': ['attribute', 'order', 'value'],
            },
        ),
    ]
