# Generated by Django 5.0.6 on 2026-05-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_filterattribute_filteroption'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, help_text="Колір фону (напр. 'bg-blue-100 text-blue-600')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_name',
            field=models.CharField(blank=True, help_text="Назва іконки з lucide-react (напр. 'Smartphone')", max_length=50, null=True),
        ),
    ]
