# Generated by Django 5.0.6 on 2026-05-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_color_category_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterattribute',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='До яких категорій належить цей фільтр', related_name='filter_attributes', to='products.category', verbose_name='Категорії'),
        ),
    ]
