# Generated by Django 5.0.6 on 2026-05-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_filterattribute_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterattribute',
            name='type',
            field=models.CharField(choices=[('checkbox', 'Чекбокси (множинний вибір)'), ('radio', 'Радіо-кнопки (одиничний вибір)'), ('color', 'Кольори'), ('range', 'Діапазон (Від / До)')], default='checkbox', max_length=20, verbose_name='Тип відображення'),
        ),
    ]
