# Generated by Django 5.0.6 on 2026-05-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_filterattribute_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_exchange',
            field=models.BooleanField(default=False, verbose_name='Обмін'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Безкоштовно'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_negotiable',
            field=models.BooleanField(default=False, verbose_name='Договірна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=1, verbose_name='Кількість'),
        ),
    ]
