# Generated by Django 5.0.6 on 2026-05-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_is_generated_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_safe_deal_enabled',
            field=models.BooleanField(default=True, verbose_name='Безпечна угода (Доставка)'),
        ),
    ]
